# This is a basic workflow to publish a new version of this package.
# It should be triggered on the creation of a new tag.
# It will update the package.json version and publish the package to npm.
# It will finally push a new commit to the master branch that includes the updated package.json version.
name: publish

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@flocasts'

            - name: Install dependencies
              run: npm ci

            - name: Update package.json version
              run: |
                  # Remove the leading 'v' if it exists
                  newVersion=$(echo "${{ github.ref_name }}" | tr -d "v")
                  currentVersion=$(jq -r .version package.json)
                  # Check if current version exists and is greater than new version
                  if [ -z "$currentVersion" ] && [ "$currentVersion" \> "$newVersion" ]
                  then
                      echo "New version number must be greater than the current version number"
                      exit 1
                  fi
                  # Update the version number in package.json
                  jq --indent 4 ".version=\"$newVersion\"" ./package.json > package.json
                  echo "Updated package.json version to $newVersion"

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Push updated package.json
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  branch: master
                  commit_message: 'Update package.json version to ${{ github.ref_name }}'
                  commit_options: '--no-verify'
                  commit_user_name: 'GitHub Actions'
